[dev]
dynamic_merge=true

[dev.redis]
password="1234"

[dev.elasticsearch]
username="elastic"
password="3ePvRYrNp5rEaEXgRHOD"

[test]
dynamic_merge=true

[test.redis]
password="1234"

[test.elasticsearch]
username="elastic"
password="3ePvRYrNp5rEaEXgRHOD"
