[default]
api_version="/api/v1"
is_dev=true

[default.logging]
logger_name="root"
filepath="../logging.conf"

[default.celery]
task_serializer="json"
accept_content=["json"]
result_serializer="json"
timezone="Asia/Seoul"
enable_utc=false
task_acks_late=true
task_reject_on_worker_lost=true
worker_prefetch_multiplier=1
worker_concurrency=4
result_expires=86400
broker_connection_retry_on_startup=true
broker_connection_max_retries=10
task_default_queue="trader.tasks"
schedule_stock_info = { hour = 8, minute = 0 }
schedule_stock_price = { hour = 16, minute = 0 }
stock_codes = ["005930", "035420", "000660", "035720", "051910", "005380", "006400", "068270"]

[default.kls]
default_token_expire_time=86400