[local]
dynamic_merge=true
api_version = "/api/v1"

[local.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[local.elasticsearch]
hosts=["localhost:9200"]

[local.kafka]
hosts=["localhost:9092"]
send_timeout=100
metadata_max_age_ms=1000
order_topic_name="trader-order-job"
default_chunk_size=1000

[local.redis]
host="localhost"
port=6379
db=0


[test]
dynamic_merge=true
api_version = "/api/v1"

[test.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[test.elasticsearch]
hosts=["localhost:9200"]

[test.kafka]
hosts=["localhost:9092"]
send_timeout=100
metadata_max_age_ms=1000
order_topic_name="trader-order-job"
default_chunk_size=1000

[test.redis]
host="localhost"
port=6379
db=0
