[local]
dynamic_merge=true
api_version = "/api/v1"

[local.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[local.elasticsearch]
hosts=["192.168.0.244:9200"]
log_hosts=["192.168.0.244:9200"]

[local.kafka]
hosts=["localhost:29092"]
send_timeout=100
metadata_max_age_ms=1000
order_topic_name="trader-order-job"
default_chunk_size=1000

[local.redis]
host="localhost"
port=6379
db=0


[test]
dynamic_merge=true
api_version = "/api/v1"

[test.elasticsearch]
hosts=["192.168.0.242:9211"]

[test.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[test.logging]
filename="/app/log/app.log"
logger_name="search42_ref"

[test.kafka]
hosts="192.168.0.242:9092"
topic="job"
send_timeout=100
metadata_max_age_ms=1000
index_job_topic_name="search42-index-job"
default_chunk_size=1000

[test.redis]
host="localhost"
port=6379
db=0