[dev]
dynamic_merge=true
api_version = "/api/v1"

[dev.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[dev.elasticsearch]
hosts=["http://localhost:9200"]

[dev.kafka]
hosts=["localhost:9094"]
send_timeout=100
metadata_max_age_ms=1000
order_topic_name="trader-order-job"
default_chunk_size=1000

[dev.redis]
host="localhost"
port=6379
db=0

[dev.celery]
broker_url="redis://localhost:6379/0"
result_backend="redis://localhost:6379/1"


[test]
dynamic_merge=true
api_version = "/api/v1"

[test.postgresql]
url="postgresql+asyncpg://admin:1234@localhost:5432"
database="stock"

[test.elasticsearch]
hosts=["http://localhost:9200"]

[test.kafka]
hosts=["localhost:9094"]
send_timeout=100
metadata_max_age_ms=1000
order_topic_name="trader-order-job"
default_chunk_size=1000

[test.redis]
host="localhost"
port=6379
db=0

[test.celery]
broker_url="redis://localhost:6379/0"
result_backend="redis://localhost:6379/1"